module.exports = deck = [
    {color:"yellow", symbol: "1"},
    {color:"yellow", symbol: "2"},
    {color:"yellow", symbol: "3"},
    {color:"yellow", symbol: "4"},
    {color:"yellow", symbol: "5"},
    {color:"yellow", symbol: "6"},
    {color:"yellow", symbol: "7"},
    {color:"yellow", symbol: "8"},
    {color:"yellow", symbol: "9"},
    {color:"yellow", symbol: "skip"},
    {color:"yellow", symbol: "draw2"},
    {color:"yellow", symbol: "reverse"},
    {color:"blue", symbol: "1"},
    {color:"blue", symbol: "2"},
    {color:"blue", symbol: "3"},
    {color:"blue", symbol: "4"},
    {color:"blue", symbol: "5"},
    {color:"blue", symbol: "6"},
    {color:"blue", symbol: "7"},
    {color:"blue", symbol: "8"},
    {color:"blue", symbol: "9"},
    {color:"blue", symbol: "skip"},
    {color:"blue", symbol: "draw2"},
    {color:"blue", symbol: "reverse"},
    {color:"red", symbol: "1"},
    {color:"red", symbol: "2"},
    {color:"red", symbol: "3"},
    {color:"red", symbol: "4"},
    {color:"red", symbol: "5"},
    {color:"red", symbol: "6"},
    {color:"red", symbol: "7"},
    {color:"red", symbol: "8"},
    {color:"red", symbol: "9"},
    {color:"red", symbol: "skip"},
    {color:"red", symbol: "draw2"},
    {color:"red", symbol: "reverse"},
    {color:"green", symbol: "1"},
    {color:"green", symbol: "2"},
    {color:"green", symbol: "3"},
    {color:"green", symbol: "4"},
    {color:"green", symbol: "5"},
    {color:"green", symbol: "6"},
    {color:"green", symbol: "7"},
    {color:"green", symbol: "8"},
    {color:"green", symbol: "9"},
    {color:"green", symbol: "skip"},
    {color:"green", symbol: "draw2"},
    {color:"green", symbol: "reverse"},
    {color: "wild", symbol: "wild"},
    {color: "wild", symbol: "wild"},
    {color: "wild", symbol: "wild"},
    {color: "wild", symbol: "draw4"},
    {color: "wild", symbol: "draw4"},
    {color: "wild", symbol: "draw4"},
    {color: "wild", symbol: "draw4"},
    {color: "wild", symbol: "draw4"}
]